
POST http://localhost:9000/api/v1/roles
Content-Type: application/json

{
    "name": "dev",
    "description": "role for developer"
}


### update role with permissions

PATCH  http://localhost:9000/api/v1/roles/21bd588e-2128-4b92-abfa-ba6a4b0c5a94
Content-Type: application/json

{
    "permissionIds": [
        "95ecb0a3-f72e-4766-bbad-79e5a35d123e",
        "09e125ad-b5ba-490b-8904-0581061e8a77",
        "64ef0fd0-58ef-49b5-be0d-2981f1dad2ff",
        "06a28cc1-93a9-46ce-9b89-af15db78a438",
        "35a777f4-e5d9-429c-bcdb-e14aee4b95c3"
    ]
}

### 
GET http://localhost:9000/api/v1/roles/21bd588e-2128-4b92-abfa-ba6a4b0c5a94

### 
GET http://localhost:9000/api/v1/roles


### search
GET http://localhost:9000/api/v1/roles?keyword=lisa

### soft delete
DELETE  http://localhost:9000/api/v1/roles/c755e588-4d21-47b0-95f4-b94c53006967
